/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AhamoveConfig {
  'apiKey' : string,
  'mobile' : [] | [string],
  'isTestMode' : boolean,
}
export interface AhamoveWorkerConfig {
  'ordersToSync' : Array<{ 'ahamoveOrderId' : string, 'orderId' : string }>,
  'apiKey' : string,
  'mobile' : string,
  'isTestMode' : boolean,
}
export interface AnalyticsEntry {
  'totalOrders' : bigint,
  'date' : string,
  'totalRevenue' : bigint,
}
export type AutoPaymentApp = { 'Sepay' : null } |
  { 'None' : null } |
  { 'Tingee' : null };
export interface BackgroundImage {
  'id' : bigint,
  'url' : string,
  'fileName' : string,
  'isDefault' : boolean,
  'uploadedAt' : bigint,
}
export interface BankDetails {
  'accountHolderName' : string,
  'bankName' : string,
  'totalAmount' : bigint,
  'accountNumber' : string,
}
export interface BannerImagePublic {
  'id' : bigint,
  'sortOrder' : bigint,
  'imageUrl' : string,
}
export interface BillItem {
  'total' : bigint,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface BkavInvoiceInfo {
  'issueDate' : string,
  'lookupCode' : string,
  'cqtCode' : string,
  'totalAfterTax' : bigint,
  'invoiceNo' : string,
  'vatAmount' : bigint,
  'vatRate' : bigint,
}
export interface BusinessBankDetails {
  'accountHolderName' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export interface BusinessProfilePatch {
  'domain' : [] | [string],
  'tingeeMerchantId' : [] | [string],
  'tingeeBankBin' : [] | [string],
  'businessName' : [] | [string],
  'email' : [] | [string],
  'tingeeVA' : [] | [string],
  'address' : [] | [string],
  'brandLogo' : [] | [string],
}
export interface BusinessProfileUpdate {
  'codSettings' : [] | [[] | [CodSettings]],
  'brand2Name' : [] | [string],
  'tableServiceHours' : [] | [string],
  'brand4Name' : [] | [string],
  'shippingFeeMode' : [] | [ShippingFeeMode],
  'deliveryServiceHours' : [] | [string],
  'brand1Name' : [] | [string],
  'stripeSecretKey' : [] | [string],
  'stripeEnabled' : [] | [boolean],
  'coordinateLatitude' : [] | [number],
  'sepayApiToken' : [] | [string],
  'autoShipperEnabled' : [] | [boolean],
  'stripePublishableKey' : [] | [string],
  'deliveryRadiusKm' : [] | [bigint],
  'brand3Name' : [] | [string],
  'autoPaymentConfirmationApp' : [] | [AutoPaymentApp],
  'bannerImageUrl' : [] | [string],
  'sepayEnabled' : [] | [boolean],
  'brand5Name' : [] | [string],
  'coordinateLongitude' : [] | [number],
  'autoPaymentConfirmationEnabled' : [] | [boolean],
}
export interface Cell { 'value' : Value, 'name' : string }
export interface CodOrderRequest {
  'deliveryAddress' : string,
  'deliveryLat' : number,
  'deliveryLng' : number,
  'recipientPhone' : string,
  'restaurantId' : RestaurantId,
  'notes' : [] | [string],
  'items' : Array<OrderItem__2>,
  'recipientName' : string,
}
export interface CodOrderResponse {
  'status' : OrderStatus,
  'orderCode' : string,
  'orderId' : OrderId,
  'message' : string,
  'totalAmount' : bigint,
}
export interface CodSettings { 'codLimit' : bigint, 'isCodAllowed' : boolean }
export interface CreateMasterCategoryRequest {
  'name' : string,
  'position' : bigint,
}
export interface CreateMasterMenuItemRequest {
  'categoryId' : bigint,
  'name' : string,
  'unit' : [] | [string],
  'description' : string,
  'imageUrl' : [] | [string],
  'price' : bigint,
  'position' : bigint,
}
export interface DeveloperProfile {
  'email' : string,
  'developerPrincipalId' : Principal,
  'businessOwnerPrincipalId' : Principal,
}
export type DeviceId = string;
export interface DeviceRecordPublic {
  'deviceToken' : string,
  'status' : { 'active' : null } |
    { 'revoked' : null },
  'lastUsedAt' : bigint,
  'createdAt' : bigint,
  'role' : StaffRole,
  'restaurantId' : bigint,
  'codeExpiry' : bigint,
  'deviceId' : DeviceId,
  'deviceName' : string,
  'activationCode' : string,
}
export interface DispatchCenterOrder {
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'recipientPhone' : string,
  'createdAt' : Timestamp,
  'shippingFee' : [] | [bigint],
  'orderCode' : string,
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'totalAmount' : bigint,
  'restaurantName' : string,
  'notes' : [] | [string],
  'isCod' : boolean,
  'items' : Array<OrderItem__2>,
  'recipientName' : string,
}
export interface DriverInfo {
  'eta' : [] | [bigint],
  'lat' : [] | [number],
  'lng' : [] | [number],
  'vehiclePlate' : string,
  'name' : string,
  'phone' : string,
}
export interface DynamicQRDeletedCallback { 'orderId' : OrderId }
export interface DynamicQRGeneratedCallback {
  'qrString' : string,
  'idempotencyKey' : string,
  'qrId' : string,
  'orderId' : OrderId,
  'billId' : string,
}
export interface DynamicQRRecordPublic {
  'status' : DynamicQRStatus,
  'qrString' : string,
  'expiresAt' : [] | [Timestamp],
  'idempotencyKey' : string,
  'totalAmountPaid' : bigint,
  'createdAt' : Timestamp,
  'qrId' : string,
  'transactionInfos' : Array<TransactionInfo>,
  'orderId' : OrderId,
  'billId' : string,
}
export type DynamicQRStatus = { 'deleted' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface DynamicQRStatusCallback {
  'status' : DynamicQRStatus,
  'totalAmountPaid' : bigint,
  'transactionInfos' : Array<TransactionInfo>,
  'orderId' : OrderId,
}
export interface DynamicQRStatusResult {
  'status' : DynamicQRStatus,
  'totalAmountPaid' : [] | [bigint],
  'transactionInfos' : [] | [string],
}
export interface DynamicQRWorkerConfig {
  'clientId' : string,
  'secretToken' : string,
  'bankBin' : string,
  'merchantId' : string,
  'workerPrincipal' : string,
  'vaAccountNumber' : string,
}
export interface EnterpriseDeviceRecord {
  'deviceToken' : string,
  'status' : { 'Active' : null } |
    { 'Revoked' : null },
  'role' : EnterpriseDeviceRole,
  'codeExpiry' : [] | [bigint],
  'deviceId' : string,
  'deviceName' : string,
  'activationCode' : [] | [string],
  'registeredAt' : bigint,
}
export type EnterpriseDeviceRole = { 'CustomerSupport' : null } |
  { 'EnterpriseDelivery' : null } |
  { 'Accounting' : null };
export type EnterprisePermission = { 'DeviceManagement' : null } |
  { 'CustomerSupport' : null } |
  { 'EnterpriseDelivery' : null } |
  { 'Accounting' : null };
export interface EnterpriseStaffPermissions {
  'permissions' : Array<EnterprisePermission>,
  'principalId' : Principal,
}
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'upgrade' : [] | [boolean],
  'status_code' : number,
}
export type InvoiceStatus = { 'Error' : null } |
  { 'Issued' : null } |
  { 'NotRequested' : null } |
  { 'Pending' : null };
export interface KioskBill {
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'changeDue' : bigint,
  'restaurantPhone' : string,
  'thankYouMsg' : string,
  'createdAt' : string,
  'itemCount' : bigint,
  'orderCode' : string,
  'website' : string,
  'amountPaid' : bigint,
  'invoiceInfo' : [] | [BkavInvoiceInfo],
  'logoUrl' : string,
  'restaurantAddr' : string,
  'restaurantName' : string,
  'tableName' : [] | [string],
  'items' : Array<BillItem>,
  'vatAmount' : bigint,
  'vatRate' : bigint,
  'subtotal' : bigint,
}
export interface MasterMenuCategory {
  'id' : bigint,
  'name' : string,
  'position' : bigint,
}
export interface MasterMenuItem {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'unit' : [] | [string],
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
  'price' : bigint,
  'position' : bigint,
}
export interface MenuCategory {
  'id' : MenuCategoryId,
  'name' : string,
  'restaurantId' : RestaurantId,
  'position' : bigint,
}
export type MenuCategoryId = bigint;
export interface MenuItem {
  'id' : MenuItemId,
  'categoryId' : MenuCategoryId,
  'name' : string,
  'unit' : [] | [string],
  'description' : string,
  'available' : boolean,
  'restaurantId' : RestaurantId,
  'imageUrl' : [] | [string],
  'price' : bigint,
}
export type MenuItemId = bigint;
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'unit' : [] | [string],
  'itemNote' : [] | [string],
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export interface OrderItem__2 {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export interface OrderPublic {
  'id' : OrderId,
  'paymentConfirmedAt' : [] | [Timestamp],
  'maCQT' : [] | [string],
  'customerName' : [] | [string],
  'status' : OrderStatus,
  'deliveryAddress' : [] | [string],
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : [] | [PaymentMethod__1],
  'customerPhone' : [] | [string],
  'paymentMethodLabel' : string,
  'createdAt' : Timestamp,
  'ahamoveOrderId' : [] | [string],
  'shippingStatus' : [] | [ShippingStatus],
  'tableIdentifier' : string,
  'shippingTransferStatus' : ShippingTransferStatus,
  'shippingFee' : [] | [bigint],
  'invoiceNo' : [] | [string],
  'orderCode' : [] | [string],
  'shipperPhone' : [] | [string],
  'dispatchNote' : [] | [string],
  'orderType' : OrderType,
  'shippingProvider' : [] | [string],
  'restaurantId' : RestaurantId,
  'invoiceDate' : [] | [string],
  'invoicePdfUrl' : [] | [string],
  'maTraCuu' : [] | [string],
  'notes' : [] | [string],
  'stripePaymentIntentId' : [] | [string],
  'isCod' : boolean,
  'items' : Array<OrderItem>,
  'driverInfo' : [] | [DriverInfo],
  'findingDriverSince' : [] | [bigint],
  'paidAt' : [] | [Timestamp],
  'invoiceStatus' : InvoiceStatus,
  'vatInfo' : [] | [VatInfo],
  'subtotal' : [] | [bigint],
  'shipperName' : [] | [string],
}
export type OrderStatus = { 'Delivered' : null } |
  { 'WaitingDriverPayment' : null } |
  { 'FindingDriver' : null } |
  { 'Ready' : null } |
  { 'WaitingDriver' : null } |
  { 'PaymentPending' : null } |
  { 'Preparing' : null } |
  { 'Cancelled' : null } |
  { 'PendingApproval' : null } |
  { 'DispatchCenter' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface OrderTrackingPublic {
  'paymentConfirmedAt' : [] | [Timestamp],
  'maCQT' : [] | [string],
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'deliveryLat' : [] | [number],
  'deliveryLng' : [] | [number],
  'ahamoveOrderId' : [] | [string],
  'shippingStatus' : [] | [ShippingStatus],
  'shippingFee' : [] | [bigint],
  'invoiceNo' : [] | [string],
  'shipperPhone' : [] | [string],
  'dispatchNote' : [] | [string],
  'orderType' : OrderType,
  'orderId' : OrderId,
  'shippingProvider' : [] | [string],
  'invoiceDate' : [] | [string],
  'invoicePdfUrl' : [] | [string],
  'maTraCuu' : [] | [string],
  'driverInfo' : [] | [DriverInfo],
  'findingDriverSince' : [] | [bigint],
  'invoiceStatus' : InvoiceStatus,
  'shipperName' : [] | [string],
}
export type OrderType = { 'DeliveryOrder' : null } |
  { 'TableOrder' : null };
export type PaymentMethod = { 'Card' : null } |
  { 'Cash' : null } |
  { 'BankTransfer' : null } |
  { 'Other' : string };
export type PaymentMethod__1 = { 'Cod' : null } |
  { 'CreditCard' : null } |
  { 'CustomerOnline' : null } |
  { 'CashierTerminal' : null } |
  { 'Stripe' : null } |
  { 'BankTransfer' : null } |
  { 'TingeeQR' : null } |
  { 'SepayQR' : null } |
  { 'ApplePay' : null };
export type PaymentStatus = { 'Failed' : null } |
  { 'SepayExpired' : null } |
  { 'Paid' : null } |
  { 'SepayPending' : null } |
  { 'TingeeExpired' : null } |
  { 'WaitingDriverPayment' : null } |
  { 'TingeePending' : null } |
  { 'Unpaid' : null } |
  { 'TingeePaid' : null } |
  { 'SepayPaid' : null } |
  { 'Pending' : null };
export interface PendingAhamoveBookingItem {
  'customerName' : string,
  'customerPhone' : string,
  'pickupLat' : [] | [number],
  'pickupLng' : [] | [number],
  'orderCode' : string,
  'dropoffLat' : [] | [number],
  'dropoffLng' : [] | [number],
  'orderId' : string,
  'restaurantId' : bigint,
  'pickupAddress' : string,
  'totalAmount' : bigint,
  'restaurantName' : string,
  'dropoffAddress' : string,
  'serviceId' : string,
}
export interface PendingDynamicQRItem {
  'idempotencyKey' : string,
  'qrId' : string,
  'orderCode' : string,
  'orderId' : OrderId,
  'operation' : PendingDynamicQROp,
  'amount' : bigint,
  'billId' : string,
}
export type PendingDynamicQROp = { 'status' : null } |
  { 'delete' : null } |
  { 'generate' : null };
export interface PendingInvoiceItem {
  'buyerAddress' : string,
  'customerCompanyName' : [] | [string],
  'createdAt' : bigint,
  'isDemo' : boolean,
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'customerCompanyAddress' : [] | [string],
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'buyerName' : string,
  'isRetailInvoice' : boolean,
  'customerTaxCode' : [] | [string],
  'vatInfo' : [] | [VatInfo],
}
export type ReservationId = bigint;
export interface ReservationPublic {
  'id' : ReservationId,
  'customerName' : string,
  'status' : ReservationStatus,
  'customerPhone' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'tableId' : [] | [TableId],
  'restaurantId' : RestaurantId,
  'durationMinutes' : bigint,
  'notes' : [] | [string],
  'partySize' : bigint,
  'customerEmail' : [] | [string],
  'timeSlot' : string,
}
export type ReservationStatus = { 'Arrived' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type RestaurantId = bigint;
export interface RestaurantLocationUpdate {
  'coordinateLatitude' : [] | [number],
  'address' : [] | [string],
  'deliveryRadiusKm' : [] | [bigint],
  'coordinateLongitude' : [] | [number],
}
export interface RestaurantPublic {
  'id' : RestaurantId,
  'brand2Name' : [] | [string],
  'tableServiceHours' : [] | [string],
  'ownerId' : Principal,
  'brand4Name' : [] | [string],
  'name' : string,
  'deliveryServiceHours' : [] | [string],
  'brand1Name' : [] | [string],
  'stripeEnabled' : boolean,
  'staffMembers' : Array<StaffMember>,
  'coordinateLatitude' : [] | [number],
  'stripePublishableKey' : [] | [string],
  'address' : string,
  'deliveryRadiusKm' : [] | [bigint],
  'brand3Name' : [] | [string],
  'autoPaymentConfirmationApp' : AutoPaymentApp,
  'bannerImageUrl' : [] | [string],
  'brand5Name' : [] | [string],
  'coordinateLongitude' : [] | [number],
  'autoPaymentConfirmationEnabled' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface RetryPolicy {
  'backoffMultiplier' : number,
  'baseDelayMs' : bigint,
  'maxRetries' : bigint,
  'maxDelayMs' : bigint,
}
export interface SavedRecipientInfo {
  'recipientPhone' : string,
  'locationName' : string,
  'recipientName' : string,
}
export interface ShipperBookingResult {
  'provider' : string,
  'shippingFee' : [] | [bigint],
  'shipperPhone' : [] | [string],
  'distanceKm' : [] | [number],
  'shipperName' : [] | [string],
}
export type ShippingFeeMode = { 'RestaurantPays' : null } |
  { 'CustomerPays' : null };
export type ShippingStatus = { 'Delivering' : null } |
  { 'SearchingShipper' : null } |
  { 'PickedUp' : null } |
  { 'ShipperAccepted' : null } |
  { 'DeliveryFailed' : null };
export type ShippingTransferStatus = { 'notStarted' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'notRequired' : null } |
  { 'failed' : null };
export interface StaffMember { 'staffId' : Principal, 'role' : StaffRole }
export type StaffRole = { 'Cashier' : null } |
  { 'Kitchen' : null } |
  { 'Delivery' : null } |
  { 'Admin' : null } |
  { 'KioskOrder' : null } |
  { 'Waiter' : null };
export interface SuggestionConfig {
  'maxDrinks' : bigint,
  'maxAddOns' : bigint,
  'suggestionsEnabled' : boolean,
}
export interface Table {
  'id' : TableId,
  'tableNumber' : string,
  'restaurantId' : RestaurantId,
  'qrCodeUrl' : string,
}
export type TableId = bigint;
export type Timestamp = bigint;
export interface TingeeBank {
  'bankBin' : string,
  'bankCode' : string,
  'bankLogo' : string,
  'bankName' : string,
  'shortName' : string,
}
export interface TingeeBanksCallback { 'banks' : Array<TingeeBank> }
export interface TransactionInfo {
  'transactionCode' : [] | [string],
  'paymentMethod' : [] | [string],
  'reference' : [] | [string],
  'bankCode' : [] | [string],
  'amount' : [] | [bigint],
  'paidAt' : [] | [string],
}
export interface UpdateMasterCategoryRequest {
  'name' : [] | [string],
  'position' : [] | [bigint],
}
export interface UpdateMasterMenuItemRequest {
  'categoryId' : [] | [bigint],
  'name' : [] | [string],
  'unit' : [] | [string],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'price' : [] | [bigint],
  'position' : [] | [bigint],
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface VatInfo {
  'accountNo' : [] | [string],
  'email' : string,
  'address' : string,
  'buyerName' : string,
  'taxCode' : [] | [string],
}
export interface WeeklyAnalyticsEntry {
  'totalOrders' : bigint,
  'totalRevenue' : bigint,
  'weekStart' : string,
}
export interface WorkerStatus {
  'workerId' : string,
  'alive' : boolean,
  'lastHeartbeatAt' : bigint,
}
export interface WorkerStatusResponse {
  'retryPolicy' : RetryPolicy,
  'workers' : Array<WorkerStatus>,
}
export interface _SERVICE {
  'activateDevice' : ActorMethod<
    [string, [] | [StaffRole]],
    {
        'ok' : {
          'deviceToken' : string,
          'role' : StaffRole,
          'restaurantId' : bigint,
          'deviceName' : string,
        }
      } |
      {
        'err' : { 'alreadyUsed' : null } |
          { 'expired' : null } |
          { 'internal' : string } |
          { 'deviceAlreadyHasRole' : null } |
          { 'notFound' : null } |
          { 'roleMismatch' : string }
      }
  >,
  'activateEnterpriseDevice' : ActorMethod<
    [string, [] | [EnterpriseDeviceRole]],
    {
        'ok' : { 'deviceToken' : string, 'role' : string, 'deviceId' : string }
      } |
      { 'err' : string }
  >,
  'addBannerImage' : ActorMethod<[string], [] | [bigint]>,
  'addEnterpriseStaff' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addStaffMember' : ActorMethod<[RestaurantId, Principal, StaffRole], boolean>,
  'assignCodDriver' : ActorMethod<
    [OrderId, Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'bookAhamoveShipper' : ActorMethod<
    [string],
    {
        'ok' : {
          'status' : string,
          'fare' : bigint,
          'ahamoveOrderId' : string,
          'distanceKm' : number,
        }
      } |
      { 'err' : string }
  >,
  'bookDriverForCodOrder' : ActorMethod<
    [OrderId],
    {
        'ok' : { 'status' : string, 'fare' : bigint, 'ahamoveOrderId' : string }
      } |
      { 'err' : string }
  >,
  'bookShipper' : ActorMethod<
    [OrderId, RestaurantId],
    { 'ok' : ShipperBookingResult } |
      { 'err' : string }
  >,
  'cancelOrder' : ActorMethod<
    [OrderId],
    { 'ok' : null } |
      {
        'err' : { 'WrongStatus' : null } |
          { 'NotFound' : null } |
          { 'Unauthorized' : null }
      }
  >,
  'cancelReservation' : ActorMethod<[ReservationId], boolean>,
  'checkCodAllowed' : ActorMethod<[bigint], boolean>,
  'checkFindingDriverTimeout' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'clearCompletedOrders' : ActorMethod<
    [RestaurantId],
    { 'ok' : bigint } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'confirmAhamoveBooking' : ActorMethod<
    [OrderId, string, bigint, string],
    {
        'ok' : { 'status' : string, 'fare' : bigint, 'ahamoveOrderId' : string }
      } |
      { 'err' : string }
  >,
  'confirmDynamicQRDeleted' : ActorMethod<
    [DynamicQRDeletedCallback],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmDynamicQRGenerated' : ActorMethod<
    [DynamicQRGeneratedCallback],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmDynamicQRStatus' : ActorMethod<
    [DynamicQRStatusCallback],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmPayment' : ActorMethod<
    [OrderId, string],
    { 'ok' : boolean } |
      { 'err' : { 'NotFound' : null } | { 'Unauthorized' : null } }
  >,
  'confirmPaymentByCashier' : ActorMethod<
    [OrderId, RestaurantId],
    { 'ok' : boolean } |
      {
        'err' : { 'NotFound' : null } |
          { 'WrongRestaurant' : null } |
          { 'Unauthorized' : null }
      }
  >,
  'confirmPaymentByTingeeStatus' : ActorMethod<
    [OrderId, bigint, [] | [string]],
    { 'ok' : boolean } |
      {
        'err' : { 'NotFound' : null } |
          { 'Unauthorized' : null } |
          { 'NotTingeePending' : null } |
          { 'AlreadyPaid' : null } |
          { 'AmountMismatch' : null }
      }
  >,
  'confirmReservation' : ActorMethod<[ReservationId], boolean>,
  'confirmTingeeBanks' : ActorMethod<
    [TingeeBanksCallback],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCategory' : ActorMethod<
    [RestaurantId, string, bigint],
    MenuCategoryId
  >,
  'createCodOrder' : ActorMethod<[CodOrderRequest], CodOrderResponse>,
  'createMasterCategory' : ActorMethod<
    [CreateMasterCategoryRequest],
    { 'ok' : MasterMenuCategory } |
      { 'err' : string }
  >,
  'createMasterMenuItem' : ActorMethod<
    [CreateMasterMenuItemRequest],
    { 'ok' : MasterMenuItem } |
      { 'err' : string }
  >,
  'createMenuItem' : ActorMethod<
    [
      RestaurantId,
      MenuCategoryId,
      string,
      string,
      bigint,
      [] | [string],
      boolean,
      [] | [string],
    ],
    MenuItemId
  >,
  'createPaymentIntent' : ActorMethod<
    [OrderId, PaymentMethod__1, RestaurantId],
    {
        'ok' : {
          'bankDetails' : [] | [BankDetails],
          'orderId' : OrderId,
          'totalAmount' : bigint,
          'currency' : string,
          'publishableKey' : [] | [string],
        }
      } |
      {
        'err' : { 'StripeNotEnabled' : null } |
          { 'NotFound' : null } |
          { 'Unauthorized' : null }
      }
  >,
  'createReservation' : ActorMethod<
    [
      RestaurantId,
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      [] | [TableId],
      [] | [string],
      [] | [string],
    ],
    ReservationId
  >,
  'createRestaurant' : ActorMethod<[string], RestaurantId>,
  'createTable' : ActorMethod<[RestaurantId, string], TableId>,
  'deleteBackgroundImage' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBannerImage' : ActorMethod<[bigint], boolean>,
  'deleteCategory' : ActorMethod<[RestaurantId, MenuCategoryId], boolean>,
  'deleteDynamicQR' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMasterCategory' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMasterMenuItem' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMenuItem' : ActorMethod<[RestaurantId, MenuItemId], boolean>,
  'deleteRestaurant' : ActorMethod<[RestaurantId], boolean>,
  'deleteTable' : ActorMethod<[RestaurantId, TableId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'findNearestRestaurant' : ActorMethod<[number, number], [] | [bigint]>,
  'generateDynamicQR' : ActorMethod<
    [string, [] | [bigint]],
    { 'ok' : DynamicQRRecordPublic } |
      { 'err' : string }
  >,
  'generateInvoiceCallbackSecret' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAhamoveConfig' : ActorMethod<[], [] | [AhamoveConfig]>,
  'getAhamoveOrderStatus' : ActorMethod<
    [OrderId],
    {
        'ok' : {
          'orderStatus' : OrderStatus,
          'ahamoveOrderId' : [] | [string],
          'shippingStatus' : [] | [ShippingStatus],
          'shippingFee' : [] | [bigint],
          'shipperPhone' : [] | [string],
          'shippingProvider' : [] | [string],
          'driverInfo' : [] | [DriverInfo],
          'shipperName' : [] | [string],
        }
      } |
      { 'err' : string }
  >,
  'getAhamoveWorkerConfig' : ActorMethod<
    [],
    { 'ok' : AhamoveWorkerConfig } |
      { 'err' : string }
  >,
  'getBannerImages' : ActorMethod<[], Array<BannerImagePublic>>,
  'getBkavInvoiceConfig' : ActorMethod<
    [],
    {
      'realGuid' : [] | [string],
      'realToken' : [] | [string],
      'demoInvoiceSerial' : string,
      'prodInvoiceSerial' : string,
      'invoiceCallbackSecret' : [] | [string],
      'useDemo' : boolean,
      'invoiceSerial' : string,
      'workerPrincipal' : [] | [string],
      'demoGuid' : [] | [string],
      'invoiceForm' : string,
      'demoToken' : [] | [string],
      'realApiUrl' : [] | [string],
      'vatRate' : bigint,
    }
  >,
  'getBusinessBankDetails' : ActorMethod<
    [[] | [string]],
    [] | [BusinessBankDetails]
  >,
  'getBusinessLogoUrl' : ActorMethod<[], string>,
  'getBusinessProfileInfo' : ActorMethod<
    [],
    {
      'domain' : [] | [string],
      'tingeeMerchantId' : [] | [string],
      'tingeeBankBin' : [] | [string],
      'businessName' : [] | [string],
      'email' : [] | [string],
      'tingeeVA' : [] | [string],
      'address' : [] | [string],
      'brandLogo' : [] | [string],
    }
  >,
  'getCodDispatchOrders' : ActorMethod<
    [],
    { 'ok' : Array<DispatchCenterOrder> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'getCodSettings' : ActorMethod<[], [] | [CodSettings]>,
  /**
   * / Returns the current canister cycle balance.
   */
  'getCycles' : ActorMethod<[], bigint>,
  'getDailyAnalytics' : ActorMethod<
    [RestaurantId, string, string],
    [] | [Array<AnalyticsEntry>]
  >,
  'getDeveloperProfile' : ActorMethod<[], [] | [DeveloperProfile]>,
  'getDispatchCenterOrders' : ActorMethod<
    [],
    { 'ok' : Array<DispatchCenterOrder> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'getDynamicQRStatus' : ActorMethod<
    [string],
    { 'ok' : DynamicQRStatusResult } |
      { 'err' : string }
  >,
  'getDynamicQRWorkerConfig' : ActorMethod<[], DynamicQRWorkerConfig>,
  'getInvoiceCallbackSecret' : ActorMethod<[string], [] | [string]>,
  'getInvoiceInfo' : ActorMethod<
    [OrderId],
    {
        'ok' : [] | [
          {
            'maCQT' : [] | [string],
            'errorMessage' : [] | [string],
            'invoiceNo' : [] | [string],
            'invoiceDate' : [] | [string],
            'invoiceStatus' : string,
          }
        ]
      } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'getInvoiceProvider' : ActorMethod<[], string>,
  'getInvoiceWorkerConfig' : ActorMethod<
    [],
    {
      'partnerToken' : string,
      'realGuid' : string,
      'realToken' : string,
      'bkavDemoEndpoint' : string,
      'partnerGUID' : string,
      'demoInvoiceSerial' : string,
      'bkavProdEndpoint' : string,
      'prodInvoiceSerial' : string,
      'invoiceCallbackSecret' : string,
      'useDemo' : boolean,
      'invoiceSerial' : string,
      'workerPrincipal' : string,
      'demoGuid' : string,
      'invoiceForm' : string,
      'demoToken' : string,
      'vatRate' : number,
    }
  >,
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getMyEnterprisePermissions' : ActorMethod<[], Array<EnterprisePermission>>,
  'getMyRestaurantFilter' : ActorMethod<
    [],
    { 'ok' : [] | [Array<RestaurantId>] } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getOrderForTracking' : ActorMethod<[OrderId], [] | [OrderTrackingPublic]>,
  'getOrderPaymentStatus' : ActorMethod<
    [OrderId],
    [] | [
      {
        'paymentConfirmedAt' : [] | [Timestamp],
        'paymentStatus' : PaymentStatus,
      }
    ]
  >,
  'getPaymentStatus' : ActorMethod<
    [OrderId],
    { 'ok' : [] | [PaymentStatus] } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'getPendingAhamoveBookings' : ActorMethod<
    [],
    Array<PendingAhamoveBookingItem>
  >,
  'getPendingCodPayments' : ActorMethod<
    [],
    [] | [
      Array<
        { 'orderTotal' : bigint, 'shippingFee' : bigint, 'orderCode' : string }
      >
    ]
  >,
  'getPendingDynamicQRs' : ActorMethod<[], Array<PendingDynamicQRItem>>,
  'getPendingInvoices' : ActorMethod<[], Array<PendingInvoiceItem>>,
  'getPublicDeveloperProfile' : ActorMethod<
    [Principal],
    [] | [DeveloperProfile]
  >,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [RestaurantPublic]>,
  'getRestaurantOverrides' : ActorMethod<[bigint], Array<bigint>>,
  'getRestaurantStripePublishableKey' : ActorMethod<
    [RestaurantId],
    [] | [string]
  >,
  'getRetryPolicy' : ActorMethod<[], RetryPolicy>,
  'getSavedRecipientInfo' : ActorMethod<[], [] | [SavedRecipientInfo]>,
  /**
   * / Returns the current schema version of the canister's data model.
   */
  'getSchemaVersion' : ActorMethod<[], bigint>,
  'getSellerInfo' : ActorMethod<
    [],
    { 'phone' : [] | [string], 'taxCode' : [] | [string] }
  >,
  'getStaffRole' : ActorMethod<[RestaurantId, Principal], [] | [StaffRole]>,
  'getSuggestionConfig' : ActorMethod<[], SuggestionConfig>,
  'getTable' : ActorMethod<[TableId], [] | [Table]>,
  'getTingeeBanks' : ActorMethod<
    [],
    { 'ok' : Array<TingeeBank> } |
      { 'err' : string }
  >,
  'getTingeeConfig' : ActorMethod<
    [],
    [] | [
      { 'clientId' : string, 'secretToken' : string, 'orderPrefix' : string }
    ]
  >,
  'getTingeeConfigForDevice' : ActorMethod<
    [string],
    [] | [
      { 'clientId' : string, 'secretToken' : string, 'orderPrefix' : string }
    ]
  >,
  'getWebhookEndpointInfo' : ActorMethod<[], string>,
  'getWeeklyAnalytics' : ActorMethod<
    [RestaurantId, string, string],
    [] | [Array<WeeklyAnalyticsEntry>]
  >,
  'getWorkerStatus' : ActorMethod<[], WorkerStatusResponse>,
  'grantEnterprisePermission' : ActorMethod<
    [Principal, EnterprisePermission],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'handleInvoiceCallback' : ActorMethod<
    [Uint8Array, Array<[string, string]>],
    { 'status' : number, 'body' : Uint8Array }
  >,
  'hasEnterprisePermission' : ActorMethod<
    [Principal, EnterprisePermission],
    boolean
  >,
  'hasInvoiceCallbackSecret' : ActorMethod<[], boolean>,
  'hasTingeeClientIdConfigured' : ActorMethod<[], boolean>,
  'hasTingeeConfigured' : ActorMethod<[], boolean>,
  'hasTingeeSecretToken' : ActorMethod<[RestaurantId], boolean>,
  'hasTingeeSecretTokenConfigured' : ActorMethod<[], boolean>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'http_request_update' : ActorMethod<[HttpRequest], HttpResponse>,
  'isEnterpriseDeliveryStaff' : ActorMethod<[], boolean>,
  'listActiveOrdersByRestaurant' : ActorMethod<
    [RestaurantId, [] | [string]],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listAllOrdersForAccounting' : ActorMethod<
    [RestaurantId],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listAllRestaurants' : ActorMethod<[], Array<RestaurantPublic>>,
  'listBackgroundImages' : ActorMethod<[], Array<BackgroundImage>>,
  'listCategories' : ActorMethod<[RestaurantId], Array<MenuCategory>>,
  'listDeliveryOrders' : ActorMethod<
    [RestaurantId, [] | [string]],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listDeliveryOrdersEnterprise' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listDeliveryOrdersForKitchen' : ActorMethod<
    [RestaurantId, [] | [string]],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listDevices' : ActorMethod<
    [bigint],
    { 'ok' : Array<DeviceRecordPublic> } |
      { 'err' : string }
  >,
  'listEnterpriseDevices' : ActorMethod<
    [],
    { 'ok' : Array<EnterpriseDeviceRecord> } |
      { 'err' : string }
  >,
  'listEnterpriseStaff' : ActorMethod<
    [],
    { 'ok' : Array<EnterpriseStaffPermissions> } |
      { 'err' : string }
  >,
  'listMasterCategories' : ActorMethod<[], Array<MasterMenuCategory>>,
  'listMasterMenuItems' : ActorMethod<[], Array<MasterMenuItem>>,
  'listMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'listMenuItemsByCategory' : ActorMethod<
    [RestaurantId, MenuCategoryId],
    Array<MenuItem>
  >,
  'listMyRestaurants' : ActorMethod<[], Array<RestaurantPublic>>,
  'listOrdersByRestaurant' : ActorMethod<
    [RestaurantId],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listOrdersByStatus' : ActorMethod<
    [RestaurantId, OrderStatus],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listOrdersByTable' : ActorMethod<
    [RestaurantId, string],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'listReservationsByRestaurant' : ActorMethod<
    [RestaurantId],
    Array<ReservationPublic>
  >,
  'listRestaurantsNearby' : ActorMethod<[number, number], Array<RestaurantId>>,
  'listTables' : ActorMethod<[RestaurantId], Array<Table>>,
  'markTingeeExpired' : ActorMethod<
    [OrderId],
    { 'ok' : boolean } |
      { 'err' : { 'NotFound' : null } | { 'Unauthorized' : null } }
  >,
  'placeDeliveryOrder' : ActorMethod<
    [
      RestaurantId,
      Array<OrderItem>,
      [] | [string],
      string,
      string,
      string,
      boolean,
      [] | [VatInfo],
      [] | [bigint],
      [] | [number],
      [] | [number],
      boolean,
    ],
    { 'ok' : { 'orderCode' : [] | [string], 'orderId' : OrderId } } |
      { 'err' : string }
  >,
  'placeOrder' : ActorMethod<
    [
      RestaurantId,
      string,
      Array<OrderItem>,
      [] | [string],
      boolean,
      [] | [VatInfo],
    ],
    { 'orderCode' : [] | [string], 'orderId' : OrderId }
  >,
  'postWorkerHeartbeat' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'printKioskBill' : ActorMethod<[OrderId], [] | [KioskBill]>,
  'receiveAhamoveWebhook' : ActorMethod<
    [string, string, [] | [DriverInfo], string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Returns the current schema version of the canister's data model.
   */
  'receiveTingeeWebhook' : ActorMethod<
    [Uint8Array, Array<[string, string]>],
    string
  >,
  'registerDevice' : ActorMethod<
    [bigint, StaffRole, string],
    { 'ok' : { 'deviceId' : string, 'activationCode' : string } } |
      { 'err' : string }
  >,
  'registerEnterpriseDevice' : ActorMethod<
    [EnterpriseDeviceRole, string],
    { 'ok' : { 'deviceId' : string, 'activationCode' : string } } |
      { 'err' : string }
  >,
  'reissueBkavInvoice' : ActorMethod<[OrderId], string>,
  'removeEnterpriseStaff' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeStaffMember' : ActorMethod<[RestaurantId, Principal], boolean>,
  'retryBookShipper' : ActorMethod<
    [string],
    {
        'ok' : {
          'fare' : bigint,
          'ahamoveOrderId' : string,
          'distanceKm' : number,
        }
      } |
      { 'err' : string }
  >,
  'revokeDevice' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'revokeEnterpriseDevice' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'revokeEnterprisePermission' : ActorMethod<
    [Principal, EnterprisePermission],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveAhamoveConfig' : ActorMethod<
    [AhamoveConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveBkavCommonConfig' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      boolean,
      bigint,
      [] | [string],
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveInvoiceProvider' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveMyRestaurantFilter' : ActorMethod<
    [Array<RestaurantId>],
    { 'ok' : null } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'saveRealBkavConfig' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveRecipientInfo' : ActorMethod<[string, string, string], undefined>,
  'saveSellerInfo' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveTingeeClientId' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveTingeeConfig' : ActorMethod<[string, string, string], undefined>,
  'saveTingeeSecretToken' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'schema' : ActorMethod<[], string>,
  'setCodSettings' : ActorMethod<
    [[] | [CodSettings]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setMasterMenuItemActive' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setMenuItemAvailability' : ActorMethod<
    [RestaurantId, MenuItemId, boolean],
    boolean
  >,
  'setRestaurantItemOverride' : ActorMethod<
    [bigint, bigint, boolean],
    undefined
  >,
  'setRetryPolicy' : ActorMethod<
    [bigint, bigint, bigint, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSuggestionConfig' : ActorMethod<
    [SuggestionConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'settleTable' : ActorMethod<
    [RestaurantId, string],
    { 'ok' : bigint } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'updateAutoPaymentConfirmationSettings' : ActorMethod<
    [RestaurantId, boolean, AutoPaymentApp],
    boolean
  >,
  'updateBannerImage' : ActorMethod<[bigint, string, bigint], boolean>,
  'updateBusinessBankDetails' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateBusinessLogoUrl' : ActorMethod<[string], boolean>,
  'updateBusinessProfile' : ActorMethod<
    [BusinessProfilePatch],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCategory' : ActorMethod<
    [RestaurantId, MenuCategoryId, string, bigint],
    boolean
  >,
  'updateMasterCategory' : ActorMethod<
    [bigint, UpdateMasterCategoryRequest],
    { 'ok' : MasterMenuCategory } |
      { 'err' : string }
  >,
  'updateMasterMenuItem' : ActorMethod<
    [bigint, UpdateMasterMenuItemRequest],
    { 'ok' : MasterMenuItem } |
      { 'err' : string }
  >,
  'updateMenuItem' : ActorMethod<
    [
      RestaurantId,
      MenuItemId,
      string,
      string,
      bigint,
      [] | [string],
      boolean,
      [] | [string],
    ],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus],
    { 'ok' : boolean } |
      { 'err' : { 'Unauthorized' : null } }
  >,
  'updateReservationStatus' : ActorMethod<
    [ReservationId, ReservationStatus],
    boolean
  >,
  'updateRestaurantLocation' : ActorMethod<
    [RestaurantId, RestaurantLocationUpdate],
    boolean
  >,
  'updateRestaurantName' : ActorMethod<[RestaurantId, string], boolean>,
  'updateRestaurantProfile' : ActorMethod<
    [RestaurantId, BusinessProfileUpdate],
    boolean
  >,
  'updateRestaurantStripeKeys' : ActorMethod<
    [RestaurantId, string, string],
    boolean
  >,
  'updateShipperStatus' : ActorMethod<
    [OrderId, string, string, ShippingStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateShippingTransferStatus' : ActorMethod<
    [string, ShippingTransferStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTable' : ActorMethod<[RestaurantId, TableId, string], boolean>,
  'uploadBackgroundImage' : ActorMethod<
    [string, string],
    { 'ok' : BackgroundImage } |
      { 'err' : string }
  >,
  'upsertDeveloperProfile' : ActorMethod<[Principal, string], DeveloperProfile>,
  'verifyDeviceToken' : ActorMethod<
    [string],
    {
        'ok' : {
          'role' : StaffRole,
          'restaurantId' : bigint,
          'deviceName' : string,
        }
      } |
      { 'err' : string }
  >,
  'verifyEnterpriseDeviceToken' : ActorMethod<
    [string],
    [] | [EnterpriseDeviceRole]
  >,
  'verifyOrderForBooking' : ActorMethod<
    [OrderId],
    {
        'ok' : {
          'status' : string,
          'valid' : boolean,
          'restaurantId' : [] | [string],
        }
      } |
      { 'err' : { 'Unauthorized' : null } }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];